version: '3'

services:
  backend:
    build: ./
    command: ['httpd-foreground']
    depends_on:
      - db
    links:
      - db
    networks:
      - lamp_demo
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/lamp-demo

  db:
    container_name: lamp_demo_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    platform: linux/x86_64
    image: 'mysql:5.7'
    networks:
      - lamp_demo
    ports:
      - 3306:3306
    volumes:
      - mysql_data_57:/var/lib/mysql


networks:
  lamp_demo:
    external: true

volumes:
  mysql_data_57:
    external: true